add some more information about hashbangctl
hashbang/hashbangctl pull request #19
Opened 2018-08-31 14:21 UTC by napcae

2018-09-01 02:58 UTC, daurnimator commented on README.md
> +	* add or delete SSH Keys
indentation here isn't consistent: it's okay to use tabs, but you still need to use a space before the `*`.
Note that usually we use `  - ` (`<space><space><hyphen><space>`) to create markdown lists. So the indentend form with tabs is: `<tab><space><space><hyphen><space>`

2018-09-01 02:59 UTC, daurnimator commented on README.md
> +Remember to save your changes, quitting the programm will discard your changes.
typo: programm

2018-09-01 02:59 UTC, daurnimator commented on README.md
> +## Installation
new line after heading.

2018-09-01 07:18 UTC, daurnimator requested changes

2018-09-01 07:18 UTC, daurnimator commented on README.md
> +- shell(``cat /etc/shells`` will list all available shells)
Use single backticks for code sections; not double.

2018-09-01 07:18 UTC, daurnimator commented on README.md
> -TODO. Document
Need two new lines at end of section

2018-09-01 07:18 UTC, daurnimator commented on README.md
> +- username
These two dot points are differently indented than the SSH ones below

2018-09-01 07:29 UTC, napcae commented on README.md
> +- username
it's intentional

2018-09-01 07:30 UTC, napcae commented on README.md
> +- username
either you change your (1)username, (2)shell or change information about your (3)ssh keys

2018-09-01 07:53 UTC, daurnimator commented on README.md
> +- username
Then you need a top level list element for the two others to be a child of

2018-09-01 16:16 UTC, daurnimator commented on README.md
> +- shell(`cat /etc/shells` will list all available shells)
space before parenthesis?

2018-09-01 16:17 UTC, daurnimator commented on README.md
> +Typing ``hashbangctl`` when you're connected to one of the hashbang servers will start the programm and give you some details about your user.
typo: programm

2018-09-02 08:47 UTC, closed without merging

2018-09-02 12:48 UTC, KellerFuchs commented
@napcae What's up?  This should be mergeable, assuming you address @daurnimator's comments.

2018-09-02 12:49 UTC, KellerFuchs commented
@daurnimator TBH, I kinda feel like this is the sort of stuff for which pushing a fix to the PR branch directly is OK.  Having a bunch of extra round-trips mostly feels tiresome  :3